GET http://localhost:3000/tasks HTTP/1.1

###
GET http://localhost:3000/tasks?status=IN_PROGRESS&search=learn HTTP/1.1

### 

POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{
    "title": "learn nestjs step 1",
    "description": "Learn nestjs controller and services"
}

###

GET http://localhost:3000/tasks/70047639-8ffc-4c89-b9e4-f941af1f5ac8 HTTP/1.1

###

DELETE http://localhost:3000/tasks/6d242e61-ad67-41b5-ad6b-b069bbf876c4 HTTP/1.1

###

PUT http://localhost:3000/tasks/70047639-8ffc-4c89-b9e4-f941af1f5ac8/status  HTTP/1.1
content-type: application/json

{
    "status": "IN_PROGRESS"
}